# .github/FUNDING.yml: Lists funding platforms where Evgenii Shiliaev accepts donations.
---
github: jekwwer
buy_me_a_coffee: jekwwer
ko_fi: jekwwer
liberapay: jekwwer
open_collective: jekwwer
patreon: jekwwer
